version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - e-commerce_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: ecommerce-backend:prod
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"  # Nginx on 80
    depends_on:
      - db
    command: sh -c "python manage.py migrate && sh -c 'service nginx start && gunicorn core.wsgi:application --bind 0.0.0.0:8000'"

volumes:
  e-commerce_postgres_data:
