version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - e-commerce_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: ghcr.io/joekariuki3/ecommerce_backend:latest
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"  # Nginx on 80
    depends_on:
      - db
    command: >
      sh -c "
        set -e
        python manage.py migrate
        service nginx start
        if ! pgrep nginx > /dev/null; then
          echo 'Nginx failed to start' >&2
          exit 1
        fi
        gunicorn core.wsgi:application --bind 0.0.0.0:8000
      "

volumes:
  e-commerce_postgres_data:
