# Generated by Django 5.2.6 on 2025-10-02 14:22

from django.db import migrations, models

import apps.catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Product image (max 5mb, JPG, PNG, WEBP)",
                null=True,
                upload_to=apps.catalog.models.product_image_path,
            ),
        ),
    ]
