name: ecommerce_backend CI Pipeline

on:
  push:
    branches: [main, develop, "feature/**"]
  pull_request:
    branches: [main, develop]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black isort bandit
      - name: Ruff lint
        run: ruff check .
      - name: Black check
        run: black --check .
      - name: Isort check
        run: isort --check-only .

  security:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Bandit security check
        run: bandit -c pyproject.toml -r core apps

      - name: Safety dependency check
        env:
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
        run: safety scan

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  e2e-playwright:
    name: E2E (Playwright)
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install playwright browsers
          python -m playwright install --with-deps chromium

      - name: Start Django dev server (background)
        env:
          ENVIRONMENT: testing
        run: |
          python manage.py migrate --noinput
          python manage.py runserver &
          # Wait for server to be ready
          for i in {1..30}; do
            if curl -sSf http://127.0.0.1:8000/ > /dev/null; then echo "Server up"; break; fi; sleep 1; done

      - name: Run Playwright tests (e2e)
        env:
          PYTEST_ADDOPTS: "--maxfail=1"
        run: |
          pytest -m e2e --tracing retain-on-failure --video retain-on-failure --screenshot only-on-failure

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            test-results/
            playwright-report/
            traces/
          if-no-files-found: ignore

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [test, e2e-playwright, security]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
